#### Numpy Array Operations

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing : ", arr[0:5])  # Output: [1 2 3 4 5]
print("Basic slicing : ", arr[5:10])   # Output: [ 6  7  8  9 10]
print("Negative indexing : ", arr[-8:-2])    # Output: [3 4 5 6 7 8]
arr_even = arr[arr % 2 == 0]
print("Even numbers : ", arr_even)  # Output: [ 2  4  6  8 10]
arr_odd = arr[arr % 2 != 0]
print("Odd numbers : ", arr_odd)  # Output: [1 3

### Sorting
arr2 = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
sorted_arr = np.sort(arr2)  
print("Sorted array : ", sorted_arr)  # Output: [1 1 2 3 3 4 5 5 6 9]

#Sort 2d array
arr_2d = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("Original 2D array : \n", arr_2d)
sorted_arr_2d = np.sort(arr_2d, axis=0)  # Sort each column
print("Sorted 2D array (by columns) : \n", sorted_arr_2d)
sorted_arr_2d_row = np.sort(arr_2d, axis=1)  # Sort each row
print("Sorted 2D array (by rows) : \n", sorted_arr_2d_row)  

### Unique elements
unique_arr = np.unique(arr2)
print("Unique elements : ", unique_arr)  # Output: [1 2 3 4 5 6 9]  

### Reshaping
arr3 = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr3.reshape(2, 3)

Basic slicing :  [1 2 3 4 5]
Basic slicing :  [ 6  7  8  9 10]
Negative indexing :  [3 4 5 6 7 8]
Even numbers :  [ 2  4  6  8 10]
Odd numbers :  [1 3 5 7 9]
Sorted array :  [1 1 2 3 3 4 5 5 6 9]
Original 2D array : 
 [[3 1 4]
 [1 5 9]
 [2 6 5]]
Sorted 2D array (by columns) : 
 [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted 2D array (by rows) : 
 [[1 3 4]
 [1 5 9]
 [2 5 6]]
Unique elements :  [1 2 3 4 5 6 9]


### Mask  Indexing and  Where



In [21]:


arr[0] = 0
mask = arr > 5 # from above code cell - arr is the original array from 1 to 10
print("Numbers greater than 5 : ", arr[mask])  # Output:numbers greater than 5 >>>  [9 6 7 8 9 10]

where_arr = np.where(arr > 5) ## same as mask but returns the indices of the elements that satisfy the condition
print("Indices of arr greater than 5 : ", where_arr)  # Output: (array([0 5, 6, 7, 8, 9]),)
print("Numbers of arr greater than 5 : ", arr[where_arr])  # Output: [9 6 7 8 9 10]


###where_arr2 = np.where(arr > 5, 1,0) ## same as mask but returns the indices of the elements that satisfy the condition
###print("Indices of arr greater than 5 : ", where_arr)  # Output: (array([0 5, 6, 7, 8, 9]),)


Numbers greater than 5 :  [ 6  7  8  9 10]
Indices of arr greater than 5 :  (array([5, 6, 7, 8, 9]),)
Numbers of arr greater than 5 :  [ 6  7  8  9 10]


##### Adding and Removing Data


In [25]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
equal_mask = arr1 == arr2   
print("Element-wise equality : ", equal_mask)  # Output: [False False  True False False]    

combinedArray = np.concatenate((arr1, arr2))
print("Combined array : ", combinedArray)  # Output: [1 2 3 4 5 5 4 3 2 1]

sumArray = arr1 + arr2
print("Element-wise sum : ", sumArray)  # Output: [6 6 6 6 6]   

print("Compatible shapes : ", arr1.shape == arr2.shape)  # Output: True

newRow = np.array([[10, 20, 30, 40, 50]])
withNewRow = np.vstack((arr1, newRow.flatten()))  # Flatten newRow
print("Array with new row : \n", withNewRow)  # Output: [[ 1  2  3  4  5]
                                              #          [10 20 30 40 50]]
newCol = np.array([55])
withNewCol = np.hstack((arr2, newCol))
print("with new column ", withNewCol)

deletedElementArray = np.delete(arr1, 2)  # Delete the element at index 2 (value 3)
print("Array after deletion : ", deletedElementArray)  # Output: [1 2 4 5]  

Element-wise equality :  [False False  True False False]
Combined array :  [1 2 3 4 5 5 4 3 2 1]
Element-wise sum :  [6 6 6 6 6]
Compatible shapes :  True
Array with new row : 
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]
with new column  [ 5  4  3  2  1 55]
Array after deletion :  [1 2 4 5]
